Repository netaxis-solutions/DRaaS, pull requests merged in 2022-03, with the labels that each got.

#96 wrong filtering fixed
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/NumberInventory.tsx
Labels: Ready for merge

#92 'remove_columns'
  src/levels/admin/components/DistributorsList/index.tsx
  src/levels/admin/components/ResellersList/index.tsx
Labels: Ready for merge

#93 Favicon change
  public/branding/default/favicon/favicon.ico
  public/favicon.ico
  public/index.html
Labels: Ready for merge

#102 validation added
  src/utils/schemas/numbersSchema.ts
Labels: Ready for merge

#97 disabled buttons for multistep added
  src/components/Modal/components/ModalButtonsWrapper.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSelection.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/SelectNumberEntitlement.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/index.tsx
  src/storage/singletons/MultiStepForm/index.ts
  src/utils/types/modal/index.ts
Labels: Ready for merge

#104 update
  src/utils/constants/menu.ts
Labels: Ready for merge

#100 fix
  public/branding/default/theme.config.json
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/styles.ts
Labels: Ready for merge

#99 Country codes
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/NumberInventory.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSelection.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSettings.tsx
Labels: Ready for merge

#101 change api
  src/levels/admin/components/ResellersList/components/AddReseller/Steps/CreateReseller.tsx
  src/storage/singletons/Reseller/index.ts
Labels: Ready for merge

#91 'Wizard'
  src/assets/unlink.svg
  src/components/Icons/Unlink.tsx
  src/components/Icons/index.ts
  src/levels/subscription/components/MsTeams/components/O365Tanant/InfoPage.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/StepperMsTeam/CancelModal/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/StepperMsTeam/CancelModal/styles.ts
  src/levels/subscription/components/MsTeams/components/O365Tanant/StepperMsTeam/Stepper.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/StepperMsTeam/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/styles.ts
  src/storage/singletons/MsTeams/Onboarding/index.ts
  src/utils/types/msTeam/index.ts
Labels: Ready for merge

#106 Default values for range setting added
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSettings.tsx
Labels: Ready for merge

#107 Question mark removed from Toast Notification
  src/levels/subscription/components/MsTeams/components/O365Admin/components/DeleteAdminModal.tsx
Labels: Ready for merge

#108 Ms teams misspeling fix
  src/utils/schemas/msTeamsCreateAdmin.ts
Labels: Ready for merge

#105 Assigned numbers disable add button
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/MyNumbers.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/MyNumbersTable.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSettings.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/styles.ts
  src/storage/singletons/Entitlements/index.ts
  src/storage/singletons/Numbers/index.tsx
Labels: Ready for merge

#110 Lengthy subscription dropdown
  src/components/Sidebar/components/SidebarDropdown/styles.ts
Labels: Ready for merge

#117 hot fix
  src/levels/subscription/components/MsTeams/components/O365Tanant/InfoPage.tsx
Labels: ready for review, Ready for merge

#114 add owners
  src/components/common/Form/FormSelect/index.tsx
  src/levels/admin/components/TenantsList/components/AddTenant/Steps/CreateTenant.tsx
  src/storage/singletons/Tenant/index.ts
  src/utils/types/form/index.ts
Labels: Ready for merge

#115 add disabled
  src/levels/subscription/components/Licenses/components/EntitlementsList/components/AddEntitlement/CreateEntitlement.tsx
Labels: Ready for merge

#103 fix pagination
  src/components/Table/components/Pagination.tsx
  src/components/Table/components/PaginationDropdown.tsx
  src/components/Table/components/PaginationNavigation.tsx
  src/components/Table/components/Toolbar.tsx
  src/components/Table/index.tsx
  src/levels/subscription/components/Licenses/components/EntitlementsList/components/AddEntitlement/CreateEntitlement.tsx
  src/levels/subscription/components/Licenses/components/EntitlementsList/index.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/MyNumbers.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/MyNumbersTable.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/NumberInventory.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSelection.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/SelectNumberEntitlement.tsx
  src/storage/singletons/TablePagination/index.ts
  src/utils/types/tableConfig/index.ts
Labels: Ready for merge

#121 update
  public/configs/default/app.config.json
Labels: Ready for merge

#116 refresh buttons added
  src/levels/subscription/components/MsTeams/components/MsTeamsUsers/components/ReloadButton.tsx
  src/levels/subscription/components/MsTeams/components/MsTeamsUsers/index.tsx
  src/levels/subscription/components/MsTeams/components/MsTeamsUsers/styles.ts
  src/storage/singletons/MsTeams/index.ts
  src/utils/types/tableConfig/index.ts
Labels: Ready for merge

#119 change field config
  src/levels/admin/components/DistributorsList/components/AddDistributor/Steps/CreateDistributor.tsx
  src/levels/admin/components/ResellersList/components/AddReseller/Steps/CreateReseller.tsx
  src/levels/admin/components/TenantsList/components/AddTenant/Steps/CreateTenant.tsx
  src/levels/tenant/components/SubscriptionsList/components/AddTenantSubscription/CreateSubscription.tsx
  src/utils/schemas/distributors.ts
  src/utils/schemas/resellers.ts
  src/utils/schemas/subscription.ts
  src/utils/schemas/tenant.ts
Labels: Ready for merge

#123 white screen after login
  src/storage/singletons/Login/index.ts
Labels: Ready for merge

#95 'add_fonts_but_cant_implement'
  public/branding/default/fonts/Font-Bold.ttf
  public/branding/default/fonts/Font-Light.ttf
  public/branding/default/fonts/Font-Medium.ttf
  public/branding/default/fonts/Font-Regular.ttf
  src/utils/constants/theme.assets.ts
  src/utils/functions/themeConfig/fonts.ts
  src/utils/functions/themeConfig/index.ts
Labels: Ready for merge

#122 checkbox alert
  public/branding/default/theme.config.json
  src/components/Table/components/styles.ts
  src/levels/subscription/components/MsTeams/components/O365Admin/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Admin/styles.ts
Labels: Ready for merge

#132 fix bug with translation in the portal
  src/components/App/index.tsx
  src/components/TopBar/components/IconsBar/LanguageBar.tsx
  src/services/Translation/index.tsx
  src/storage/singletons/Translate/index.ts
Labels: Ready for merge

#133 remove symbol from column in msTeam users table
  src/levels/subscription/components/MsTeams/components/MsTeamsUsers/components/OtherLicenses.tsx
Labels: Ready for merge

#134 fix delete modal with long name
  src/levels/admin/components/DistributorsList/components/DeleteDistributorModal/styles.ts
  src/levels/admin/components/ResellersList/components/DeleteResellerModal/styles.ts
  src/levels/admin/components/TenantsList/components/DeleteTenantModal/styles.ts
  src/levels/subscription/components/Licenses/components/EntitlementsList/components/DeleteEntitlement/styles.ts
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/DeleteModal/styles.ts
  src/levels/tenant/components/SubscriptionsList/components/DeleteTenantSubscriptions/styles.ts
Labels: Ready for merge

#120 empty field in select Owner
  src/levels/admin/components/ResellersList/components/AddReseller/Steps/CreateReseller.tsx
  src/levels/admin/components/TenantsList/components/AddTenant/Steps/CreateTenant.tsx
  src/storage/singletons/Reseller/index.ts
  src/storage/singletons/Tenant/index.ts
  src/utils/types/resellers/index.ts
Labels: Ready for merge

#126 disabled buttons msTeam admin if we have active wizard steps process
  src/levels/subscription/components/MsTeams/components/O365Admin/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Admin/styles.ts
Labels: Ready for merge

#136 fix msteam steps error
  src/storage/singletons/MsTeams/Onboarding/index.ts
Labels: Ready for merge

#139 add tooltip to numbers range size
  public/branding/default/theme.config.json
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSettings.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/styles.ts
Labels: Ready for merge

#138 fix rules in tenant table
  src/storage/singletons/Tenants/index.ts
Labels: Ready for merge

#137 add fix for 2fa auth
  src/levels/authorization/Login/components/TwoFactorAuthenticationForm.tsx
  src/storage/singletons/Login/index.ts
Labels: Ready for merge

#129 change side bar menu
  src/components/Sidebar/index.tsx
  src/components/Sidebar/styles.ts
  src/storage/singletons/SidebarConfig/index.ts
Labels: Ready for merge

#131 add new functional with status already linked
  public/branding/default/theme.config.json
  src/levels/subscription/components/MsTeams/components/O365Admin/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Admin/styles.ts
  src/levels/subscription/components/MsTeams/components/O365Tanant/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/styles.ts
Labels: Ready for merge

#146 Skeleton
  src/components/Loader/index.tsx
  src/components/Sidebar/Skeleton.tsx
  src/components/Sidebar/index.tsx
  src/components/Table/Skeleton.tsx
  src/components/Table/styles.ts
  src/levels/admin/components/DistributorsList/index.tsx
  src/levels/admin/components/ResellersList/index.tsx
  src/levels/admin/components/TenantsList/index.tsx
  src/levels/subscription/components/Licenses/components/EntitlementsList/index.tsx
  src/levels/subscription/components/Licenses/components/LicensesList/index.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/MyNumbersTable.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/ReservedNumbers/index.tsx
  src/levels/tenant/components/SubscriptionsList/index.tsx
  src/storage/singletons/PendingQueries/index.ts
  src/utils/functions/getIsLoading/index.ts
Labels: Ready for merge

#125 bug fixed table dropdownt page size
  src/components/Table/components/Pagination.tsx
  src/components/Table/components/PaginationDropdown.tsx
  src/components/Table/index.tsx
  src/levels/subscription/components/Licenses/components/LicensesList/index.tsx
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/RangeSelection.tsx
  src/storage/singletons/TablePagination/index.ts
Labels: Changes required

#141 remove text if we have a admin in wizard
  src/levels/subscription/components/MsTeams/components/O365Admin/index.tsx
  src/levels/subscription/components/MsTeams/components/O365Tanant/index.tsx
Labels: ready for review

#142 remove old columns in select numbers and add new with Number Left
  src/levels/subscription/components/SubscriptionNumbersPage/TabsContent/AssignedNumbers/components/MultistepModal/Steps/SelectNumberEntitlement.tsx
Labels: ready for review

#143 fix 2 bugs in auth and msTeam user list
  src/levels/authorization/Login/components/styles.tsx
  src/levels/subscription/components/MsTeams/components/MsTeamsUsers/components/OtherLicenses.tsx
  src/storage/singletons/MsTeams/Onboarding/index.ts
Labels: ready for review
